config/routes.rb
Rails.application.routes.draw do
  root 'home#index'


  devise_for :users
  get 'home/index'
  get 'home/index'
  match 'home/edit', via: [:get]
  match 'home/update', via: [:post, :patch]

  get 'admin', to: 'admin#index'
  get "admin/:id/edit" => "admin#edit", as: "user_edit"
  get "admin/:id/transactions" => "admin#transactions", as: "user_transactions"
  get "admin/transactions" => "admin#all_transactions", as: "all_transactions"
  patch 'admin/:id/update' => 'admin#update', as: 'user_update_by_admin'

  # get 'transactions/deposit'
  resources :transactions


	mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # user.is_admin?, 
      if user.is_admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def created_on
    created_at.strftime("%D %I:%M %p")
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  TRANSACTION_TYPE = ['Deposit', 'Withdraw']

  belongs_to :user

  validates :t_type, inclusion: { in: TRANSACTION_TYPE, message: "Transaction type Must be #{TRANSACTION_TYPE.join(' or ')}" }  # transaction type
  validate :check_funds
  after_create :update_funds

  def pin
  end

  def process_transactoin(pin)
    if is_deposit?
      save
    elsif is_withdraw?
      if user.pin == pin
        save
      else
        errors.add(:enterd, "PIN is not valid!")
        false
      end
    end
  end

  def is_deposit?
    t_type == 'Deposit'
  end

  def is_withdraw?
    t_type == 'Withdraw'
  end

  private

  def update_funds
    user.update(amount: user.amount + amount) if is_deposit?
    user.update(amount: user.amount - amount) if is_withdraw?
  end

  def check_funds
    return if is_deposit?
    errors.add(:you, 'don\'t have sufficient amount') unless user.amount >= amount
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable


  has_many :transactions

  validates_uniqueness_of :card, :unless => proc{|obj| obj.card.blank? }
  validates :card, :presence => true, :unless => "pin.blank?"
  validates :pin, :presence => true, :if => "!card.blank?"

  def is_admin?
    email == 'admin@admin.com'
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_admin_user

  def index
  	@users = User.all
  end

  def edit
  	@user = User.find_by(id: params[:id])
  	redirect_to admin_path, alert: "User not found" unless @user
  end

  def transactions
    @user = User.find_by(id: params['id'])
    filename = "#{@user.email.split('@')[0]}.xls"
    respond_to do |format|
      format.html
      format.xls { headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" }
    end
  end

  def all_transactions
    @transactions = Transaction.includes(:user).paginate(:page => params[:page], :per_page => params[:per_page] || 2)
    respond_to do |format|
      format.html
      format.xls { headers["Content-Disposition"] = "attachment; filename=allTransactions.xls" }
    end

  end


  def update
  	@user = User.find_by(id: params[:id])
    respond_to do |format|
	  	if @user && @user.update(user_params)
	      format.html { redirect_to admin_path, notice: 'Updated Successfully' }
	  	else
	    	format.html { render :edit }
	  	end
  	end
  end

  private

  def authenticate_admin_user
  	unless current_user && current_user.is_admin?
  		redirect_to root_path, alert: "You are not autherised to access this page!"
  	end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :dob, :ph, :is_active, :card, :pin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, except: [:index]


  def index
    redirect_to(admin_path, notice: "Welcome to admin panel") if current_user && current_user.is_admin?
  end

  def edit
    @user = current_user
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to home_edit_path, notice: 'Updated Successfully' }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :dob, :ph)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :authenticate_user!

  def index
    @transactions = current_user.transactions
  end

  def new
    @transaction = current_user.transactions.build  
  end
  
  def create
    @transaction = current_user.transactions.build(transaction_params.slice("amount", "t_type"))

    respond_to do |format|
      if @transaction.valid? && @transaction.process_transactoin(get_pin)
        format.html { redirect_to transactions_path, notice: 'Transaction done successfully' }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end


  def deposit
    
  end

  private

  def transaction_params
    params.require(:transaction).permit(:amount, :t_type, :card, :pin)
  end

  def get_pin
    pin_hash = transaction_params.slice("pin").to_h
    pin_hash["pin"]
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	def is_active(boolean=nil)
		boolean ? "Active" : "De Active"
	end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/all_transactions.html.erb
<h1>Transactions</h1>
<%if @transactions.size > 0%>
  <%= link_to "Export Data to spreadsheet", all_transactions_path(format: "xls", per_page: params[:per_page]), class: "btn btn-info" %>

  <br>
  <div class="margin-5">
    <%= link_to "Display 2 records Per Page",  all_transactions_path(:per_page =>2), class: "btn btn-warning"%>
    <%= link_to "Display 5 records Per Page",  all_transactions_path(:per_page =>5), class: "btn btn-danger"%>
    <%= link_to "Display 10 records Per Page",  all_transactions_path(:per_page =>10), class: "btn btn-success"%>
  </div>


  <table class="table table-responsive">
    <thead>
      <tr>
        <th>Account Holder Name</th>
        <th>Email</th>
        <th>Type</th>
        <th>Amount</th>
        <th>Date</th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.user.full_name %></td>
          <td><%= transaction.user.email %></td>
          <td><%= transaction.t_type %></td>
          <td><%= transaction.amount %></td>
          <td><%= transaction.created_on %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%else%>
  <hr>
  <h5>No transactions avilable !</h5>
<%end%>

<%= will_paginate @transactions %>

app/views/admin/all_transactions.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Account Holder Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Transaction Type</Data></Cell>
        <Cell><Data ss:Type="String">Amount</Data></Cell>
        <Cell><Data ss:Type="String">Transaction Date</Data></Cell>
      </Row>
    <% @transactions.each do |transaction| %>
      <Row>
        <Cell><Data ss:Type="String"><%= transaction.user.full_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.t_type %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= transaction.amount %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.created_on %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/edit.html.erb
<% @user.errors.full_messages.each do |message|%>
<div class="alert alert-danger">
  <p>
    <%=message%>
    <span class="padding-5 pointer pull-right" onclick="closeMe(this)">x</span>
  </p>
</div>
<%end%>
<div class="row">
  <%= form_for @user, as: :user, url: user_update_by_admin_path(@user), method: :patch do |f| %>

    <div class="col-lg-4">
      <%= render partial: 'common/user_fields', locals: {f: f}%>
    </div>
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
      <div class="form-group">
        <%= f.label :status%>
        <div>
          <%= f.check_box :is_active%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email%>
        <p class="user-info">
          <%= @user.email%>
        </p>
      </div>
      <div class="form-group">
        <%= f.label :card%>
        <%= f.text_field :card, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :pin%>
        <%= f.text_field :pin, class: "form-control" %>
      </div>

    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= f.submit 'Update Profile', class: 'btn btn-success' %>
        <%= link_to "Home", root_path, class: 'btn btn-warning' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/index.html.erb
<div class="row">
	<div class="col-lg-6">
		
		<table class="table table-hover">
		    <thead>
		      <tr>
		        <th>Firstname</th>
		        <th>Lastname</th>
		        <th>Status</th>
		        <th>Email</th>
		        <th>Card No</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<%@users.each do |user|%>
			      <tr>
							<td><%= user.first_name%></td>
							<td><%= user.last_name%></td>
							<td><%= is_active(user.is_active) %></td>
							<td><%= user.email%></td>
							<td><%= user.card%></td>

			        <td><%= link_to 'Edit', user_edit_path(user), class: "btn btn-warning" %></td>
			        <td><%= link_to 'Transactions', user_transactions_path(user), class: "btn btn-info" %></td>

			      </tr>
		    	<%end%>
		    </tbody>
		  </table>


	</div>
</div>

app/views/admin/transactions.html.erb
<h1>Transactions</h1>
<%if @user.transactions.size > 0%>
  <%= link_to "Export Data to spreadsheet", user_transactions_path(format: "xls"), class: "btn btn-info" %>
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>Name</th>
        <th>Card No.</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @user.full_name %></td>
        <td><%= @user.card %></td>
      </tr>
    </tbody>
  </table>
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>Type</th>
        <th>Amount</th>
        <th>Date</th>
      </tr>
    </thead>

    <tbody>
      <% @user.transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.t_type %></td>
          <td><%= transaction.amount %></td>
          <td><%= transaction.created_on %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%else%>
  <hr>
  <h5>No transactions avilable !</h5>
<%end%>

app/views/admin/transactions.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Transaction Type</Data></Cell>
        <Cell><Data ss:Type="String">Amount</Data></Cell>
        <Cell><Data ss:Type="String">Transaction Date</Data></Cell>
      </Row>
    <% @user.transactions.each do |transaction| %>
      <Row>
        <Cell><Data ss:Type="String"><%= transaction.t_type %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= transaction.amount %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.created_on %></Data></Cell>
      </Row>
    <% end %>
    	<Row></Row>
    	<Row>TRANSACTION BELONGS TO</Row>
    	<Row>
        <Cell><Data ss:Type="String"><%= @user.full_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @user.email %></Data></Cell>
        <Cell><Data ss:Type="String">Card: <%= @user.card %></Data></Cell>
    	</Row>
    </Table>
  </Worksheet>
</Workbook>

app/views/common/_disable_alert.erb
<div class="alert alert-danger">
  <strong>Danger!</strong> You need to activate by the Manager
</div>

app/views/common/_user_fields.html.erb
<div class="form-group">
	<%= f.label :first_name%>
	<%= f.text_field :first_name, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :last_name%>
	<%= f.text_field :last_name, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :phone_number%>
	<%= f.number_field :ph, class: "form-control" %>
</div>

app/views/home/edit.html.erb
<div class="row">
	<%= form_for @user, as: :user, url: home_update_path, method: :patch do |f| %>

		<div class="col-lg-4">
			<%= render partial: 'common/user_fields', locals: {f: f}%>
		</div>
		<div class="col-lg-2"></div>
		<div class="col-lg-4">
			<div class="form-group">
				<%= f.label :status%>
				<p class="user-info"> <%= is_active(@user.is_active) %> </p>
			</div>
			<div class="form-group">
				<%= f.label :email%>
				<p class="user-info">
					<%= @user.email%>
				</p>
			</div>
			<div class="form-group">
				<%= f.label :amount%>
				<p class="user-info">
					<%= @user.amount%>
				</p>
			</div>
			<div class="form-group">
				<%= f.label :card%>
				<p class="user-info">
					<%= @user.card.present? ? @user.card : "You don't have ATM card"%>
				</p>
			</div>
			<div class="form-group">
				<%= f.label :pin%>
				<p class="user-info">
					<%= @user.pin.present? ? @user.pin : "You don't have ATM pin"%>
				</p>
			</div>


		</div>
		<div class="col-lg-12 margin-top-bottom-20">
			<%= f.submit 'Update Profile', class: 'btn btn-success' %>
			<%= link_to "Home", root_path, class: 'btn btn-warning' %>
		</div>
	<% end %>
</div>

app/views/home/index.html.erb
<!-- <div id='messages'></div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BankingSystem" %></title>


    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>


<script type="text/javascript">
  

</script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">BankingSystem</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%if current_user && current_user.is_admin? %>
              <li><%= link_to "Managements", admin_path  %></li>
              <li><%= link_to "Transactions", user_transactions_path(current_user)  %></li>
              <li><%= link_to "All Transactions", all_transactions_path  %></li>
            <%elsif current_user %>
              <li><%= link_to "Profile", home_edit_path  %></li>
              <li><%= link_to "New Transaction", new_transaction_path %></li>
              <li><%= link_to "My Transaction", transactions_path %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= render partial: 'common/disable_alert' if current_user && !current_user.is_active %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <div id="user_nav">
              <% if user_signed_in? %>
                <p class="user-info">Available Amount: <strong> <%= current_user.try(:amount) %> </strong></p>
                Signed in as <%= current_user.email %>. Not you?
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
              <% end %>
            </div>            
          </div>
        </div>
      </div>

      <footer class="navbar-fixed-bottom align-center">
        <p>&copy; Company 2018</p>
      </footer>
    </div>

  </body>
</html>

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<table class="table table-responsive">
  <thead>
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.t_type %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.created_on %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/new.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-5">
      <div class="form-group">
        <%= f.label :transaction_type %>
        <%= f.select :t_type, options_for_select(Transaction::TRANSACTION_TYPE, @transaction.t_type), { prompt: 'Select Transaction Type' }, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.label :amount %>
        <%= f.number_field :amount, class: 'form-control', min: 1, placeholder: "Amount" %>
      </div>

      <div class="form-group pin-column">
        <%= f.label :pin %>
        <%= f.number_field :pin, class: 'form-control', min: 4, placeholder: "PIN" %>
        <span class="hint">Optional for deposit</span>
      </div>

      <div class="actions">
        <%= f.submit :class => 'btn btn-success' %>
      </div>
    </div>
    
    <div class="col-lg-5">
      <div class="form-group">
        <%= f.label :card %>
        <p class="user-info-disable">
          <%= current_user.card.present? ? current_user.card : "You don't have a ATM card"%>
        </p>
      </div>
      
    </div>
  </div>

<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>